In [1]:
import pandas as pd
import collections
from operator import itemgetter
from collections import OrderedDict

# Common words in different aspects of the same entities.

## This will help to create definite boundaries between the aspects

# Seat

In [180]:
seat_list=[]
seat_aspect_list=[]
seat_id_list=[]

df=pd.read_csv(r"C:/Users/Vaibhav/Downloads/FinalLabelsv2/FinalLabelsv2/Seat.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['Seat'].notna()]
seat_list.extend(df1['Seat'])
seat_id_list.extend(df1['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df1['Aspect']:
    seat_aspect_list.append(asp.lower())


r'''df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/SeatAspects.csv")
df3=df2[df2['Group'].notna()]
df3=df3[df3['Seat'].notna()]
seat_list.extend(df3['Seat'])
seat_id_list.extend(df3['id'])
#aspect_list=list(df1['Aspect'])
for asp in df3['Group']:
    seat_aspect_list.append(asp.lower())'''

'df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/SeatAspects.csv")\ndf3=df2[df2[\'Group\'].notna()]\ndf3=df3[df3[\'Seat\'].notna()]\nseat_list.extend(df3[\'Seat\'])\nseat_id_list.extend(df3[\'id\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df3[\'Group\']:\n    seat_aspect_list.append(asp.lower())'

In [181]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop_words = list(stopwords.words('english'))
newStop = ['was', 'and', 'the', 'to', 'in', 'of', 'a', 'an', 'is', 'were', 'for', 'with', 'are', 'one', 'our', 'gave', 'have',
           'me', 'an', 'i', 'or', 'had', 'did', 'get', 'made', 'take', 'given', 'told', 'let', 'us','!']#, "n't"]
stop_words = stop_words+newStop

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vaibhav\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [182]:
vlsta=[]
vlstb=[]
vlstid=[]
for i in range(len(seat_list)):
    seat_list[i]=seat_list[i].replace("n't",' not')
    #vlst=[w for w in seat_list[i].split() and w not in stop_words]
    for word in seat_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(seat_aspect_list[i])
                vlstid.append(seat_id_list[i])
    #for word in vlst#
    
df_seat_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')

In [183]:
df_seat_new

          id         Word      Aspect
0       2948          leg     comfort
1081    3828     headrest     comfort
1080    3828   adjustable     comfort
1079    3828      leather     comfort
1078    3828        seats     comfort
1077    3826    headrests     comfort
1076    3826   adjustable     comfort
1075    3826       winged     comfort
1074    3826      leather     comfort
1082    3832          leg     comfort
1073    3826  upholstered     comfort
1071    3825   adjustable     comfort
1070    3825       winged     comfort
1069    3825  comfortable     comfort
1068    3825        cover     comfort
1067    3825      leather     comfort
1066    3825        lassy     comfort
1065    3825       unique     comfort
1064    3825        seats     comfort
1072    3825    headrests     comfort
1063    3824      legroom     comfort
1083    3832         room     comfort
1085    3832     enhanced     comfort
1103  100026        could     comfort
1102  100026         seat     comfort
1101  100026        small     comfort
1100  100026          sit     comfort
1099  100026    transport     comfort
1098  100026      animals     comfort
1097  100026         like     comfort
...      ...          ...         ...
1132  100034    adjusting  operations
1133  100034         seat  operations
424     3437    preferred  operations
1137  100039     specific  operations
1138  100039      seating  operations
427     3437        seats  operations
437     3455         seat  operations
438     3455  allocations  operations
439     3457   fixblocked  operations
484     3478       middle  operations
483     3478          pay  operations
482     3478        seats  operations
481     3478          pay  operations
475     3474         seat  operations
474     3474     reserved  operations
473     3474     disabled  operations
472     3472       pocket  operations
471     3472         seat  operations
470     3472         mpty  operations
459     3465          sea  operations
458     3465       window  operations
449     3464     fullflat  operations
448     3464         seat  operations
447     3464       crumbs  operations
446     3464       stains  operations
445     3464         seat  operations
444     3464        dirty  operations
440     3457         back  operations
1054    3821    selection  operations
830     3690      seating  operations

[1662 rows x 3 columns]

In [184]:
#df_seat_new.to_csv(r'\seat_new.csv')

In [185]:
seat_comfort=[]
seat_operations=[]
seat_space=[]


for i in range(len(vlstb)):
    if vlstb[i]=='comfort':
        seat_comfort.append(vlsta[i])
    if vlstb[i]=='operations':
        seat_operations.append(vlsta[i])
    if vlstb[i]=='space':
        seat_space.append(vlsta[i])

In [186]:
seat_comfort_d=collections.Counter(seat_comfort)
seat_comfort_d=OrderedDict(sorted(seat_comfort_d.items(), key=itemgetter(1),reverse=True))
#sorted(seat_comfort_d.items(), key=lambda x: x[1],reverse=True)

seat_operations_d=collections.Counter(seat_operations)
seat_operations_d=OrderedDict(sorted(seat_operations_d.items(), key=itemgetter(1),reverse=True))

seat_space_d=collections.Counter(seat_space)
seat_space_d=OrderedDict(sorted(seat_space_d.items(), key=itemgetter(1),reverse=True))

In [187]:
seat_comfort_operations_d=dict()

for element in seat_comfort_d.keys() & seat_operations_d.keys():
#    print(element,min(seat_comfort_d[element],seat_operations_d[element]))
    seat_comfort_operations_d[element]=min(seat_comfort_d[element],seat_operations_d[element])
seat_comfort_operations_d=OrderedDict(sorted(seat_comfort_operations_d.items(), key=itemgetter(1),reverse=True))

In [188]:
seat_comfort_space_d=dict()

for element in seat_comfort_d.keys() & seat_space_d.keys():
#    print(element,min(seat_comfort_d[element],seat_operations_d[element]))
    seat_comfort_space_d[element]=min(seat_comfort_d[element],seat_space_d[element])
seat_comfort_space_d=OrderedDict(sorted(seat_comfort_space_d.items(), key=itemgetter(1),reverse=True))

In [189]:
seat_space_operations_d=dict()

for element in seat_space_d.keys() & seat_operations_d.keys():
#    print(element,min(seat_comfort_d[element],seat_operations_d[element]))
    seat_space_operations_d[element]=min(seat_space_d[element],seat_operations_d[element])
seat_space_operations_d=OrderedDict(sorted(seat_space_operations_d.items(), key=itemgetter(1),reverse=True))

In [190]:
seat_comfort_operations_space_d=dict()

for element in seat_comfort_operations_d.keys() & seat_comfort_space_d.keys():
#    print(element,min(seat_comfort_d[element],seat_operations_d[element]))
    seat_comfort_operations_space_d[element]=min(seat_comfort_operations_d[element],seat_comfort_space_d[element])
seat_comfort_operations_space_d=OrderedDict(sorted(seat_comfort_operations_space_d.items(), key=itemgetter(1),reverse=True))

In [191]:
seat_operations_df=pd.DataFrame({'Word':list(seat_operations_d.keys()),'Count':list(seat_operations_d.values())})
seat_operations_df

              Word  Count
0             seat     90
1            seats     70
2          seating     11
3             paid     10
4            extra      9
5            aisle      8
6         bassinet      7
7           window      7
8        selection      7
9            class      6
10        together      6
11          change      5
12       preferred      5
13             pay      5
14        business      4
15           empty      4
16             row      4
17            good      4
18          middle      4
19           broke      4
20         changed      4
21           chose      3
22            rows      3
23            book      3
24         reserve      3
25            side      3
26         average      3
27         economy      3
28          choose      3
29       extremely      3
..             ...    ...
217      adjusting      1
218       specific      1
219  unfortunately      1
220         people      1
221    congregated      1
222           near      1
223        prebook      1
224       standard      1
225        changes      1
226     separately      1
227          first      1
228           room      1
229      confirmed      1
230           pick      1
231    accordingly      1
232            pre      1
233         wanted      1
234         little      1
235          rooms      1
236           move      1
237         beside      1
238           time      1
239    differently      1
240          abled      1
241         person      1
242        sitting      1
243        honored      1
244      seatsthey      1
245         chosen      1
246           poor      1

[247 rows x 2 columns]

In [192]:
seat_space_df=pd.DataFrame({'Word':list(seat_space_d.keys()),'Count':list(seat_space_d.values())})
seat_space_df

Empty DataFrame
Columns: [Word, Count]
Index: []

In [193]:
seat_comfort_operations_df=pd.DataFrame({'Word':list(seat_comfort_operations_d.keys()),'Count':list(seat_comfort_operations_d.values())})
seat_comfort_operations_df

             Word  Count
0            seat     73
1           seats     70
2         seating     11
3           extra      7
4            good      4
5          broken      3
6       extremely      3
7            best      2
8             leg      2
9          enough      2
10        legroom      2
11          could      2
12            old      2
13         cannot      2
14            sit      2
15       together      2
16        recline      2
17         seated      2
18           back      2
19         choose      1
20           tiny      1
21           flat      1
22       separate      1
23       bulkhead      1
24         barely      1
25           rest      1
26          short      1
27       standard      1
28           side      1
29        rubbish      1
30        covered      1
31        limited      1
32           next      1
33      available      1
34       pushback      1
35           room      1
36         little      1
37          table      1
38  configuration      1
39      preferred      1
40           full      1
41        pockets      1
42        average      1
43          close      1
44           move      1
45          chair      1
46         covers      1
47          clean      1
48      scattered      1
49           poor      1
50        economy      1
51         bigger      1
52         button      1
53         decent      1
54           even      1
55      excellent      1
56            arm      1
57        damaged      1

In [194]:
seat_comfort_space_df=pd.DataFrame({'Word':list(seat_comfort_space_d.keys()),'Count':list(seat_comfort_space_d.values())})
seat_comfort_space_df

Empty DataFrame
Columns: [Word, Count]
Index: []

In [195]:
seat_comfort_operations_df=pd.DataFrame({'Word':list(seat_comfort_operations_d.keys()),'Count':list(seat_comfort_operations_d.values())})
seat_comfort_operations_df

             Word  Count
0            seat     73
1           seats     70
2         seating     11
3           extra      7
4            good      4
5          broken      3
6       extremely      3
7            best      2
8             leg      2
9          enough      2
10        legroom      2
11          could      2
12            old      2
13         cannot      2
14            sit      2
15       together      2
16        recline      2
17         seated      2
18           back      2
19         choose      1
20           tiny      1
21           flat      1
22       separate      1
23       bulkhead      1
24         barely      1
25           rest      1
26          short      1
27       standard      1
28           side      1
29        rubbish      1
30        covered      1
31        limited      1
32           next      1
33      available      1
34       pushback      1
35           room      1
36         little      1
37          table      1
38  configuration      1
39      preferred      1
40           full      1
41        pockets      1
42        average      1
43          close      1
44           move      1
45          chair      1
46         covers      1
47          clean      1
48      scattered      1
49           poor      1
50        economy      1
51         bigger      1
52         button      1
53         decent      1
54           even      1
55      excellent      1
56            arm      1
57        damaged      1

In [196]:
seat_comfort_operations_space_df=pd.DataFrame({'Word':list(seat_comfort_operations_space_d.keys()),'Count':list(seat_comfort_operations_space_d.values())})
seat_comfort_operations_space_df

Empty DataFrame
Columns: [Word, Count]
Index: []

# Cabin

In [197]:
cabin_list=[]
cabin_aspect_list=[]
cabin_id_list=[]

df=pd.read_csv(r"C:/Users/Vaibhav/Downloads/FinalLabelsv2/FinalLabelsv2/Cabin.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['Cabin'].notna()]
cabin_list.extend(df1['Cabin'])
cabin_id_list.extend(df1['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df1['Aspect']:
    cabin_aspect_list.append(asp.lower())


r'''df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/CabinAspects.csv")
df3=df2[df2['Groups'].notna()]
df3=df3[df3['Cabin'].notna()]
cabin_list.extend(df3['Cabin'])
cabin_id_list.extend(df3['id'])
#aspect_list=list(df1['Aspect'])
for asp in df3['Groups']:
    cabin_aspect_list.append(asp.lower())'''

'df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/CabinAspects.csv")\ndf3=df2[df2[\'Groups\'].notna()]\ndf3=df3[df3[\'Cabin\'].notna()]\ncabin_list.extend(df3[\'Cabin\'])\ncabin_id_list.extend(df3[\'id\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df3[\'Groups\']:\n    cabin_aspect_list.append(asp.lower())'

In [198]:
cabin_list

['dirty',
 'cabin',
 'uncomfortably',
 'cold',
 'temperature',
 'spotlessly',
 'clean',
 'overhead',
 'space',
 'plenty',
 'smelt',
 'so',
 'bad',
 'cabin',
 'change',
 'very',
 'tight',
 'too',
 'cold',
 'small',
 'overhead',
 'locker',
 'overhead',
 'locker',
 'business',
 'cabins',
 'user',
 'friendly',
 'not',
 'clean',
 'smell',
 'was',
 'horrible',
 'clean',
 'condition',
 'really',
 'dirty',
 'no',
 'leg',
 'room',
 'very',
 'clean',
 'additional',
 'underseat',
 'bag',
 'kids',
 'are',
 'freezing',
 'sell',
 'you',
 'blankets',
 'cabin',
 'toilets',
 'restricted',
 'toilets',
 'very',
 'small',
 'renting',
 'a',
 'blanket',
 'flight',
 'was',
 'comfortable',
 'seatbelt',
 'signs',
 'extremely',
 'strong',
 'ac',
 'temperature',
 'degree',
 'of',
 'comfort',
 'wellkept',
 'wellmaintained',
 'added',
 'comfort',
 'very',
 'comfortable',
 'old',
 'aisles',
 'very',
 'narrow',
 'and',
 'tighter',
 'the',
 'space',
 'clean',
 'plane',
 'air',
 'conditioning',
 'was',
 'leaking',
 'general',
 'space',
 'cabin',
 'was',
 'well',
 'lit',
 'overhead',
 'storage',
 'full',
 'storage',
 'compartments',
 'wide',
 'open',
 'cabin',
 'overheads',
 'space',
 'optimization',
 'very',
 'bad',
 'fleet',
 'aging',
 'old',
 'space',
 'between',
 'the',
 'bed',
 'and',
 'the',
 'table',
 'is',
 'very',
 'limited',
 'find',
 'space',
 'for',
 'everyoneâ€™s',
 'hand',
 'luggage',
 'old',
 'plane',
 'hadnâ€™t',
 'been',
 'fully',
 'cleaned',
 'very',
 'dated',
 'and',
 'tatty',
 'cabin',
 'hot',
 'plane',
 'very',
 'old',
 'broken',
 'airconditioning',
 'clean',
 'old',
 'and',
 'uncomfortable',
 'extremely',
 'cold',
 'smaller',
 'planes',
 'smooth',
 'do',
 'not',
 'dim',
 'the',
 'cabin',
 'lights',
 'cabin',
 'was',
 'very',
 'cold',
 'not',
 'fresh',
 'cabin',
 'nice',
 'and',
 'comfortable',
 'the',
 'aircraft',
 'was',
 'clean',
 'cabin',
 'is',
 'clean',
 'very',
 'clean',
 'mperature',
 'on',
 'board',
 'extremely',
 'hot',
 'cabin',
 'was',
 'clean',
 'old',
 'air',
 'conditioner',
 'broke',
 'interior',
 'of',
 'the',
 'plane',
 'was',
 'very',
 'dated',
 'cabin',
 'spilling',
 'trays',
 'aircraft',
 'clean',
 'faded',
 'cabin',
 'lighting',
 'oldest',
 'and',
 'in',
 'quite',
 'poor',
 'condition',
 'cabin',
 'was',
 'in',
 'need',
 'of',
 'a',
 'refresh',
 'clean',
 'was',
 'showing',
 'its',
 'age',
 'cabin',
 'looked',
 'very',
 'tired',
 'aircraft',
 'was',
 'looking',
 'clean',
 'aircraft',
 'clean',
 'new',
 'comfortable',
 'aircraft',
 'without',
 'air',
 'conditioning',
 'aircraft',
 'looked',
 'new',
 'and',
 'clean',
 'plane',
 'was',
 'immaculate',
 'worn',
 'out',
 'out',
 'of',
 'date',
 'lay',
 'out',
 'old',
 'style',
 'aircraft',
 'space',
 'was',
 'very',
 'cramped',
 'significantly',
 'more',
 'people',
 'washroom',
 'was',
 'not',
 'even',
 'clean',
 'not',
 'a',
 'clean',
 'maintained',
 'temperature',
 'was',
 'very',
 'low',
 'cabin',
 'was',
 'completely',
 'full',
 'too',
 'crowded',
 'improve',
 'cleanliness',
 'shabby',
 'condition',
 'non',
 'working',
 'air',
 'conditioning',
 'cabins',
 'minimum',
 'air',
 'venting',
 'very',
 'warm',
 'ac',
 'was',
 'having',
 'issues',
 'not',
 'much',
 'privacy',
 'lighter',
 'side',
 'flight',
 'was',
 'not',
 'full',
 'new',
 'and',
 'clean',
 'interiors',
 'were',
 'outdated',
 'and',
 'in',
 'tatters',
 'cabin',
 'was',
 'very',
 'smelly',
 'cabin',
 'was',
 'very',
 'fresh',
 'and',
 'clean',
 'very',
 'bad',
 'cramped',
 'no',
 'carryon',
 'overhead',
 'space',
 'runs',
 'out',
 'of',
 'overhead',
 'baggage',
 'space',
 'looked',
 'brand',
 'well',
 'worth',
 'pretty',
 'modern',
 'tight',
 'pitch',
 'cheesy',
 'smell',
 'air',
 'is',
 'still',
 'not',
 'working',
 'stuffy',
 'small',
 'plenty',
 'of',
 'room',
 'for',
 'more',
 'bags',
 'cabin',
 'clean',
 'clean',
 'fresh',
 'and',
 'well',
 'looked',
 'refurbished',
 'cleanliness',
 'ambience',
 'fairly',
 'nice',
 'mighty',
 'clean',
 'clean',
 'up',
 'the',
 'deck',
 'unhygienic',
 'tidy',
 'hot',
 'desert',
 'winds',
 'clean',
 'plenty',
 'of',
 'space',
 'clean',
 'seperate',
 'the',
 'cabins',
 'clean',
 'very',
 'clean',
 'environment',
 'friendly',
 'inflight',
 'comfort',
 'cleanliness',
 'to',
 'comfort',
 'perfect',
 'colourful',
 'and',
 'beautiful',
 'cabin',
 'was',
 'cramped',
 'calming',
 'interior',
 'is',
 'fresh',
 'well',
 'maintained',
 'and',
 'clean',
 'cramped',
 'decor',
 'amazed',
 'interior',
 'is',
 'spacious',
 'modern',
 'good',
 'clean',
 'and',
 'tidy',
 'cleanliness',
 'offputting',
 'looked',
 'like',
 'old',
 'clean',
 'colour',
 'scheme',
 'new',
 'and',
 'clean',
 'interior',
 'was',
 'fantastically',
 'decorated',
 'new',
 'cabins',
 'cabins',
 'are',
 'clean',
 'clean',
 'refreshingly',
 'lean',
 'cabins',
 'quite',
 'warm',
 'reduce',
 'the',
 'temperature',
 'beautiful',
 'colours',
 'cabin',
 'smells',
 'good',
 'cleaned',
 'thoroughly',
 'wellmaintained',
 'interiors',
 'clean',
 'cabins',
 'cabin',
 'baggage',
 'smells',
 'good',
 'appears',
 'clean',
 'spotless',
 'spacious',
 'and',
 'comfortable',
 'lots',
 'of',
 'legroom',
 'ambience',
 'and',
 'quietness',
 'older',
 'fit-out',
 'really',
 'outdated',
 'unable',
 'to',
 'open',
 'really',
 'old',
 'plenty',
 'of',
 'storage',
 'quietness',
 'too',
 'narrow',
 'too',
 'narrow',
 'smell',
 'everything',
 'wasn’t',
 'able',
 'to',
 'breath',
 'neatness',
 'of',
 'the',
 'cabin',
 'looked',
 'as',
 'good',
 'planes',
 'were',
 'clean',
 'space',
 'clean',
 'and',
 'neat',
 'very',
 'clean',
 'cabin',
 'was',
 'clean',
 'impressed',
 'by',
 'space',
 'comfort',
 'cleanliness',
 'ac',
 'very',
 'strong',
 'nothing',
 'fancy',
 'clean',
 'and',
 'tidy',
 'reasonably',
 'new',
 'newish',
 'clean',
 'temperature',
 'of',
 'the',
 'cabin',
 'cold',
 'empty',
 'cans',
 'lying',
 'quiet',
 'clean',
 'planes',
 'are',
 'clean',
 'can’t',
 'breathe',
 'aisles',
 'were',
 'so',
 'narrow',
 'relatively',
 'new',
 'wide',
 'body',
 'bathrooms',
 'were',
 'keep',
 'cleaner',
 'throughout',
 'everything',
 'was',
 'cleaner',
 'lots',
 'of',
 'room',
 'ample',
 'overhead',
 'bin',
 'space',
 'lane',
 'is',
 'old',
 'creaky',
 'barely',
 'enough',
 'space',
 'to',
 'walk',
 'plane',
 'was',
 'clean',
 'good',
 'clean',
 'cabin',
 'nice',
 'accommodations',
 'newer',
 'cleanliness',
 'tables',
 'were',
 'filthy',
 'lights',
 'in',
 'ceiling',
 'were',
 'out',
 'of',
 'order',
 'nice',
 'cabin',
 'cabin',
 'well',
 'ventilated',
 'toilet',
 'clean',
 'clean',
 'and',
 'correctly',
 'managed',
 'common',
 'places',
 'nice',
 'and',
 'quiet',
 'flight',
 'clean',
 'it',
 'was',
 'cramped',
 'plane',
 'was',
 'modern',
 'clean',
 'plane',
 'was',
 'clean',
 'nothing',
 'worn',
 'or',
 'broken',
 'nice',
 'clean',
 'plane',
 'completely',
 'taken',
 'aback',
 'when',
 'i',
 'saw',
 'the',
 'flight',
 'interiors',
 'toilet',
 'malfunction',
 'plane',
 'was',
 'very',
 'nice',
 'full',
 'and',
 'big',
 'plane',
 'really',
 'old',
 'plane',
 'washrooms',
 'were',
 'spacious',
 'clean',
 'toilets',
 'clean',
 'new',
 'aircrafts',
 'leg',
 'space',
 'was',
 'superior',
 'ample',
 'room',
 'more',
 'space',
 'leg',
 'room',
 'is',
 'adequate',
 'good',
 'leg',
 'room',
 'clean',
 'comfy',
 'plane',
 'was',
 'clean',
 'tidy',
 'more',
 'leg',
 'room',
 'extra',
 'legroom',
 'more',
 'leg',
 'room',
 'clean',
 'flight',
 'brilliant',
 'leg',
 'room',
 'more',
 'room',
 'clean',
 'tidy',
 'more',
 'space',
 'new',
 'aircraft',
 'llegroom',
 'quiet',
 'and',
 'smooth',
 'legroom',
 'was',
 'good',
 'plane',
 'was',
 'huge',
 'interior',
 'designer',
 'of',
 'this',
 'plane',
 'bright',
 'and',
 'yet',
 'soothing',
 'colors',
 'lots',
 'of',
 'space',
 'extra',
 'legroom',
 'freezing',
 'cold',
 'fumes',
 'from',
 'refueling',
 'cabin',
 'cramped',
 'badly',
 'designed',
 'clean',
 'more',
 'legroom',
 'plenty',
 'of',
 'legroom',
 'loads',
 'of',
 'leg',
 'room',
 'fine',
 'for',
 'leg',
 'room',
 'clean',
 'plane',
 'seemed',
 'new',
 'plane',
 'was',
 'clean',
 'well',
 'presented',
 'plane',
 'was',
 'ok',
 'more',
 'legroom',
 'not',
 'even',
 'a',
 'foot',
 'rest',
 'felt',
 'smaller',
 'plane',
 'cramming',
 'not',
 'leaving',
 'space',
 'for',
 'distancing',
 'extra',
 'fees',
 'for',
 'the',
 'extra',
 'legroom',
 'dirty',
 'plane',
 'more',
 'legroom',
 'modernised',
 'clean',
 'footrest',
 'was',
 'broken',
 'plane',
 'was',
 'an',
 'old',
 'more',
 'modern',
 'not',
 'much',
 'legroom',
 'quite',
 'noisy',
 'being',
 'behind',
 'the',
 'engines',
 'cabin',
 'was',
 'really',
 'clean',
 'good',
 'space',
 'leg',
 'space',
 'is',
 'very',
 'less',
 'neat',
 'and',
 'clean',
 'more',
 'leg',
 'spaces',
 'better',
 'interiors',
 'the',
 'leg',
 'room',
 'satisfactory',
 'enough',
 'leg',
 'space',
 'clean',
 'and',
 'efficiently',
 'managed',
 'very',
 'small',
 'size',
 'flight',
 'was',
 'very',
 'very',
 'small',
 'very',
 'congested',
 'not',
 'enough',
 'leg',
 'room',
 'pretty',
 'decent',
 'neat',
 'colours',
 'are',
 'vibrant',
 'hardly',
 'any',
 'leg',
 'room',
 'left',
 'good',
 'leg',
 'space',
 'lots',
 'of',
 'leg',
 'room',
 'brand',
 'new',
 'spotless',
 'ambience',
 'clean',
 'aircraft',
 'newer',
 'plane',
 'new',
 'aircraft',
 'was',
 'nice',
 'clean',
 'aircraft',
 'was',
 'nice',
 'clean',
 'aircraft',
 'was',
 'nice',
 'clean']

In [199]:
set(cabin_aspect_list)

{'condition', 'fragrance', 'maintainance', 'size', 'temperature'}

In [200]:
cabin_aspect_list

['condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'fragrance',
 'fragrance',
 'fragrance',
 'condition',
 'condition',
 'size',
 'size',
 'temperature',
 'temperature',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'fragrance',
 'fragrance',
 'fragrance',
 'condition',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'fragrance',
 'fragrance',
 'fragrance',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'fragrance',
 'fragrance',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'size',
 'size',
 'size',
 'condition',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'size',
 'size',
 'size',
 'size',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'fragrance',
 'size',
 'size',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'condition',
 'condition',
 'fragrance',
 'fragrance',
 'fragrance',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'condition',
 'fragrance',
 'fragrance',
 'condition',
 'condition',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'fragrance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'temperature',
 'temperature',
 'temperature',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'fragrance',
 'fragrance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'temperature',
 'temperature',
 'temperature',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'temperature',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'size',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance',
 'maintainance']

In [201]:
vlsta=[]
vlstb=[]
vlstid=[]

for i in range(len(cabin_list)):
    cabin_list[i]=cabin_list[i].replace("n't",' not')
    #vlst=[w for w in cabin_list[i].split() and w not in stop_words]
    for word in cabin_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(cabin_aspect_list[i])
                vlstid.append(cabin_id_list[i])

In [202]:
df_cabin_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')
#df_cabin_new.to_csv(r'\cabin_new.csv')

In [203]:
cabin_condition=[]
cabin_fragrance=[]
cabin_space=[]
cabin_temperature=[]

for i in range(len(vlstb)):
    if vlstb[i]=='condition':
        cabin_condition.append(vlsta[i])
    if vlstb[i]=='fragrance':
        cabin_fragrance.append(vlsta[i])
    if vlstb[i]=='space':
        cabin_space.append(vlsta[i])
    if vlstb[i]=='temperature':
        cabin_temperature.append(vlsta[i])



cabin_condition_d=collections.Counter(cabin_condition)
cabin_condition_d=OrderedDict(sorted(cabin_condition_d.items(), key=itemgetter(1),reverse=True))
#sorted(cabin_condition_d.items(), key=lambda x: x[1],reverse=True)

cabin_fragrance_d=collections.Counter(cabin_fragrance)
cabin_fragrance_d=OrderedDict(sorted(cabin_fragrance_d.items(), key=itemgetter(1),reverse=True))

cabin_space_d=collections.Counter(cabin_space)
cabin_space_d=OrderedDict(sorted(cabin_space_d.items(), key=itemgetter(1),reverse=True))

cabin_temperature_d=collections.Counter(cabin_temperature)
cabin_temperature_d=OrderedDict(sorted(cabin_temperature_d.items(), key=itemgetter(1),reverse=True))

In [204]:
cabin_condition_fragrance_d=dict()
for element in cabin_condition_d.keys() & cabin_fragrance_d.keys():
    cabin_condition_fragrance_d[element]=min(cabin_condition_d[element],cabin_fragrance_d[element])
cabin_condition_fragrance_d=OrderedDict(sorted(cabin_condition_fragrance_d.items(), key=itemgetter(1),reverse=True))   
cabin_condition_fragrance_df=pd.DataFrame({'Word':list(cabin_condition_fragrance_d.keys()),'Count':list(cabin_condition_fragrance_d.values())})
    
cabin_condition_space_d=dict()
for element in cabin_condition_d.keys() & cabin_space_d.keys():
    cabin_condition_space_d[element]=min(cabin_condition_d[element],cabin_space_d[element])
cabin_condition_space_d=OrderedDict(sorted(cabin_condition_space_d.items(), key=itemgetter(1),reverse=True))
cabin_condition_space_df=pd.DataFrame({'Word':list(cabin_condition_space_d.keys()),'Count':list(cabin_condition_space_d.values())})

cabin_space_fragrance_d=dict()
for element in cabin_space_d.keys() & cabin_fragrance_d.keys():
    cabin_space_fragrance_d[element]=min(cabin_space_d[element],cabin_fragrance_d[element])    
cabin_space_fragrance_d=OrderedDict(sorted(cabin_space_fragrance_d.items(), key=itemgetter(1),reverse=True))
cabin_space_fragrance_df=pd.DataFrame({'Word':list(cabin_space_fragrance_d.keys()),'Count':list(cabin_space_fragrance_d.values())})

cabin_condition_temperature_d=dict()
for element in cabin_condition_d.keys() & cabin_temperature_d.keys():
    cabin_condition_temperature_d[element]=min(cabin_condition_d[element],cabin_temperature_d[element])
cabin_condition_temperature_d=OrderedDict(sorted(cabin_condition_temperature_d.items(), key=itemgetter(1),reverse=True))
cabin_condition_temperature_df=pd.DataFrame({'Word':list(cabin_condition_temperature_d.keys()),'Count':list(cabin_condition_temperature_d.values())})
    
cabin_fragrance_temperature_d=dict()
for element in cabin_fragrance_d.keys() & cabin_temperature_d.keys():
    cabin_fragrance_temperature_d[element]=min(cabin_fragrance_d[element],cabin_temperature_d[element])
cabin_fragrance_temperature_d=OrderedDict(sorted(cabin_fragrance_temperature_d.items(), key=itemgetter(1),reverse=True))
cabin_fragrance_temperature_df=pd.DataFrame({'Word':list(cabin_fragrance_temperature_d.keys()),'Count':list(cabin_fragrance_temperature_d.values())})
   
cabin_space_temperature_d=dict()
for element in cabin_space_d.keys() & cabin_temperature_d.keys():
    cabin_space_temperature_d[element]=min(cabin_space_d[element],cabin_temperature_d[element])
cabin_space_temperature_d=OrderedDict(sorted(cabin_space_temperature_d.items(), key=itemgetter(1),reverse=True))
cabin_space_temperature_df=pd.DataFrame({'Word':list(cabin_space_temperature_d.keys()),'Count':list(cabin_space_temperature_d.values())})

x=dict()
cabin_condition_space_fragrance_temperature_d=dict() #all
for element in cabin_space_fragrance_d.keys() & cabin_condition_d.keys():
#    print(element,min(cabin_space_d[element],cabin_space_d[element]))
    x[element]=min(cabin_space_fragrance_d[element],cabin_condition_d[element])
x=OrderedDict(sorted(x.items(), key=itemgetter(1),reverse=True))
for element in x.keys() & cabin_temperature_d.keys():
#    print(element,min(cabin_space_d[element],cabin_space_d[element]))
    cabin_condition_space_fragrance_temperature_d[element]=min(x[element],cabin_temperature_d[element])
cabin_condition_space_fragrance_temperature_d=OrderedDict(sorted(cabin_condition_space_fragrance_temperature_d.items(), key=itemgetter(1),reverse=True))
cabin_condition_space_fragrance_temperature_df=pd.DataFrame({'Word':list(cabin_condition_space_fragrance_temperature_d.keys()),'Count':list(cabin_condition_space_fragrance_temperature_d.values())})

In [205]:
cabin_condition_fragrance_df

    Word  Count
0  cabin      5
1  fresh      2
2  clean      1
3    bad      1
4   good      1

In [206]:
cabin_condition_space_df

Empty DataFrame
Columns: [Word, Count]
Index: []

In [207]:
cabin_space_fragrance_df

Empty DataFrame
Columns: [Word, Count]
Index: []

In [208]:
cabin_condition_temperature_df

     Word  Count
0   cabin      3
1    well      1
2  cabins      1
3   plane      1
4     old      1
5   quite      1

In [209]:
cabin_fragrance_temperature_df

    Word  Count
0  cabin      3

In [210]:
cabin_space_temperature_df

Empty DataFrame
Columns: [Word, Count]
Index: []

In [211]:
cabin_condition_space_fragrance_temperature_df

Empty DataFrame
Columns: [Word, Count]
Index: []

# Possession

In [212]:
possession_list=[]
possession_aspect_list=[]
possession_id_list=[]

df=pd.read_csv(r"C:/Users/Vaibhav/Downloads/FinalLabelsv2/FinalLabelsv2/Pos.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['Possession'].notna()]
possession_list.extend(df1['Possession'])
possession_id_list.extend(df1['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df1['Aspect']:
    possession_aspect_list.append(asp.lower())


r'''df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/PossessionAspects.csv")
df3=df2[df2['Groups'].notna()]
df3=df3[df3['Possession'].notna()]
possession_list.extend(df3['Possession'])
possession_id_list.extend(df3['id'])
#aspect_list=list(df1['Aspect'])
for asp in df3['Groups']:
    possession_aspect_list.append(asp.lower())'''

'df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/PossessionAspects.csv")\ndf3=df2[df2[\'Groups\'].notna()]\ndf3=df3[df3[\'Possession\'].notna()]\npossession_list.extend(df3[\'Possession\'])\npossession_id_list.extend(df3[\'id\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df3[\'Groups\']:\n    possession_aspect_list.append(asp.lower())'

In [213]:
set(possession_aspect_list)

{'general', 'handling'}

In [214]:

vlsta=[]
vlstb=[]
vlstid=[]

for i in range(len(possession_list)):
    possession_list[i]=possession_list[i].replace("n't",' not')
    #vlst=[w for w in possession_list[i].split() and w not in stop_words]
    for word in possession_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(possession_aspect_list[i])
                vlstid.append(possession_id_list[i]) 

df_possession_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')
#df_possession_new.to_csv(r'\possession_new.csv')

In [215]:
possession_general=[]
possession_handling=[]



for i in range(len(vlstb)):
    if vlstb[i]=='general':
        possession_general.append(vlsta[i])
    if vlstb[i]=='handling':
        possession_handling.append(vlsta[i])


possession_general_d=collections.Counter(possession_general)
possession_general_d=OrderedDict(sorted(possession_general_d.items(), key=itemgetter(1),reverse=True))

possession_handling_d=collections.Counter(possession_handling)
possession_handling_d=OrderedDict(sorted(possession_handling_d.items(), key=itemgetter(1),reverse=True))


possession_general_handling_d=dict()
for element in possession_general_d.keys() & possession_handling_d.keys():
#    print(element,min(possession_general_d[element],possession_handling_d[element]))
    possession_general_handling_d[element]=min(possession_general_d[element],possession_handling_d[element])
possession_general_handling_d=OrderedDict(sorted(possession_general_handling_d.items(), key=itemgetter(1),reverse=True))   
possession_general_handling_df=pd.DataFrame({'Word':list(possession_general_handling_d.keys()),'Count':list(possession_general_handling_d.values())})

In [216]:
possession_general_handling_df

         Word  Count
0     luggage     35
1     baggage     29
2         bag     25
3        bags     15
4    suitcase      7
5       check      7
6     checked      6
7   delivered      2
8        free      2
9       items      2
10   transfer      2
11     wasted      1
12  allowance      1
13       duty      1
14      weigh      1
15       easy      1
16        two      1
17      never      1
18       lost      1
19      claim      1
20       left      1
21    missing      1
22   handling      1
23     uggage      1

# Staff

In [217]:
staff_list=[]
staff_aspect_list=[]
staff_id_list=[]

df=pd.read_csv(r"C:/Users/Vaibhav/Downloads/FinalLabelsv2/FinalLabelsv2/Staff.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['Staff'].notna()]
staff_list.extend(df1['Staff'])
staff_id_list.extend(df1['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df1['Aspect']:
    staff_aspect_list.append(asp.lower())


r'''df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/StaffAspects.csv")
df3=df2[df2['Groups'].notna()]
df3=df3[df3['Staff'].notna()]
staff_list.extend(df3['Staff'])
staff_id_list.extend(df3['id'])
#aspect_list=list(df1['Aspect'])
for asp in df3['Groups']:
    staff_aspect_list.append(asp.lower())'''

'df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/StaffAspects.csv")\ndf3=df2[df2[\'Groups\'].notna()]\ndf3=df3[df3[\'Staff\'].notna()]\nstaff_list.extend(df3[\'Staff\'])\nstaff_id_list.extend(df3[\'id\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df3[\'Groups\']:\n    staff_aspect_list.append(asp.lower())'

In [218]:
set(staff_aspect_list)

{'behaviour', 'general'}

In [219]:
vlsta=[]
vlstb=[]
vlstid=[]

for i in range(len(staff_list)):
    staff_list[i]=staff_list[i].replace("n't",' not')
    #vlst=[w for w in staff_list[i].split() and w not in stop_words]
    for word in staff_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(staff_aspect_list[i])
                vlstid.append(staff_id_list[i]) 

                
df_staff_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')
#df_staff_new.to_csv(r'\staff_new.csv')

In [220]:
staff_general=[]
staff_behaviour=[]



for i in range(len(vlstb)):
    if vlstb[i]=='general':
        staff_general.append(vlsta[i])
    if vlstb[i]=='behaviour':
        staff_behaviour.append(vlsta[i])


staff_general_d=collections.Counter(staff_general)
staff_general_d=OrderedDict(sorted(staff_general_d.items(), key=itemgetter(1),reverse=True))

staff_behaviour_d=collections.Counter(staff_behaviour)
staff_behaviour_d=OrderedDict(sorted(staff_behaviour_d.items(), key=itemgetter(1),reverse=True))


staff_general_behaviour_d=dict()
for element in staff_general_d.keys() & staff_behaviour_d.keys():
#    print(element,min(staff_general_d[element],staff_behaviour_d[element]))
    staff_general_behaviour_d[element]=min(staff_general_d[element],staff_behaviour_d[element])
staff_general_behaviour_d=OrderedDict(sorted(staff_general_behaviour_d.items(), key=itemgetter(1),reverse=True))   
staff_general_behaviour_df=pd.DataFrame({'Word':list(staff_general_behaviour_d.keys()),'Count':list(staff_general_behaviour_d.values())})

In [221]:
staff_general_behaviour_df.where(staff_general_behaviour_df['Count']==2).dropna()

              Word  Count
33           pilot    2.0
34          agents    2.0
35         ignored    2.0
36       employees    2.0
37      management    2.0
38           speak    2.0
39  representative    2.0
40      stewardess    2.0
41              ok    2.0
42          answer    2.0
43         apology    2.0
44       personnel    2.0
45         special    2.0
46    announcement    2.0
47       passenger    2.0
48  responsibility    2.0
49       apologies    2.0
50          poorly    2.0
51         captain    2.0
52             job    2.0
53         refused    2.0
54           clear    2.0
55           super    2.0

# In-flight

In [222]:
inflight_list=[]
inflight_aspect_list=[]
inflight_id_list=[]

df=pd.read_csv(r"C:/Users/Vaibhav/Downloads/FinalLabelsv2/FinalLabelsv2/Inf.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['In-flight service'].notna()]
inflight_list.extend(df1['In-flight service'])
inflight_id_list.extend(df1['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df1['Aspect']:
    inflight_aspect_list.append(asp.lower())

r'''
df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/InflightAspects.csv")
df3=df2[df2['Groups'].notna()]
df3=df3[df3['In-flight service'].notna()]
inflight_list.extend(df3['In-flight service'])
inflight_id_list.extend(df3['id'])
#aspect_list=list(df1['Aspect'])
for asp in df3['Groups']:
    inflight_aspect_list.append(asp.lower())'''

'\ndf2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/InflightAspects.csv")\ndf3=df2[df2[\'Groups\'].notna()]\ndf3=df3[df3[\'In-flight service\'].notna()]\ninflight_list.extend(df3[\'In-flight service\'])\ninflight_id_list.extend(df3[\'id\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df3[\'Groups\']:\n    inflight_aspect_list.append(asp.lower())'

In [223]:
set(inflight_aspect_list)

{'facility', 'operations'}

In [224]:
vlsta=[]
vlstb=[]
vlstid=[]

for i in range(len(inflight_list)):
    inflight_list[i]=inflight_list[i].replace("n't",' not')
    #vlst=[w for w in inflight_list[i].split() and w not in stop_words]
    for word in inflight_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(inflight_aspect_list[i])
                vlstid.append(inflight_id_list[i]) 

                
df_inflight_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')
#df_inflight_new.to_csv(r'\inflight_new.csv')

In [225]:

inflight_facility=[]
inflight_operations=[]



for i in range(len(vlstb)):
    if vlstb[i]=='facility':
        inflight_facility.append(vlsta[i])
    if vlstb[i]=='operations':
        inflight_operations.append(vlsta[i])


inflight_facility_d=collections.Counter(inflight_facility)
inflight_facility_d=OrderedDict(sorted(inflight_facility_d.items(), key=itemgetter(1),reverse=True))

inflight_operations_d=collections.Counter(inflight_operations)
inflight_operations_d=OrderedDict(sorted(inflight_operations_d.items(), key=itemgetter(1),reverse=True))


inflight_facility_operations_d=dict()
for element in inflight_facility_d.keys() & inflight_operations_d.keys():
#    print(element,min(inflight_facility_d[element],inflight_operations_d[element]))
    inflight_facility_operations_d[element]=min(inflight_facility_d[element],inflight_operations_d[element])
inflight_facility_operations_d=OrderedDict(sorted(inflight_facility_operations_d.items(), key=itemgetter(1),reverse=True))   
inflight_facility_operations_df=pd.DataFrame({'Word':list(inflight_facility_operations_d.keys()),'Count':list(inflight_facility_operations_d.values())})

In [226]:
inflight_facility_operations_df

              Word  Count
0          service     14
1             time      5
2             wifi      5
3         inflight      4
4            class      3
5           flight      3
6         customer      2
7         business      2
8             good      2
9             nice      2
10            poor      2
11           clean      2
12            best      1
13          really      1
14           drink      1
15             air      1
16         special      1
17     hospitality      1
18         working      1
19        services      1
20          safety      1
21           dirty      1
22         program      1
23         blanket      1
24     unorganized      1
25           first      1
26        magazine      1
27          better      1
28           short      1
29         quality      1
..             ...    ...
38          smooth      1
39            free      1
40        terrible      1
41           board      1
42         offered      1
43           worst      1
44         arrival      1
45            sign      1
46       technical      1
47        aircraft      1
48          prompt      1
49      everything      1
50             use      1
51           quick      1
52        internet      1
53            much      1
54   entertainment      1
55        horrible      1
56  disembarkation      1
57       extremely      1
58         comfort      1
59   uncomfortable      1
60       efficient      1
61          worked      1
62            warm      1
63      efficiency      1
64           great      1
65        catering      1
66            used      1
67           delay      1

[68 rows x 2 columns]

# Food

In [227]:
food_list=[]
food_aspect_list=[]
food_id_list=[]

df=pd.read_csv(r"C:/Users/Vaibhav/Downloads/FinalLabelsv2/FinalLabelsv2/Food.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['Food'].notna()]
food_list.extend(df1['Food'])
food_id_list.extend(df1['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df1['Aspect']:
    food_aspect_list.append(asp.lower())


r'''df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/FoodAspects.csv")
df3=df2[df2['Groups'].notna()]
df3=df3[df3['Food'].notna()]
food_list.extend(df3['Food'])
food_id_list.extend(df3['id'])
#aspect_list=list(df1['Aspect'])
for asp in df3['Groups']:
    food_aspect_list.append(asp.lower())'''

'df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/FoodAspects.csv")\ndf3=df2[df2[\'Groups\'].notna()]\ndf3=df3[df3[\'Food\'].notna()]\nfood_list.extend(df3[\'Food\'])\nfood_id_list.extend(df3[\'id\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df3[\'Groups\']:\n    food_aspect_list.append(asp.lower())'

In [228]:
set(food_aspect_list)

{'service', 'taste', 'temperature'}

In [229]:
vlsta=[]
vlstb=[]
vlstid=[]

for i in range(len(food_list)):
    food_list[i]=food_list[i].replace("n't",' not')
    #vlst=[w for w in food_list[i].split() and w not in stop_words]
    for word in food_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(food_aspect_list[i])
                vlstid.append(food_id_list[i]) 

                
df_food_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')
#df_food_new.to_csv(r'\food_new.csv')

In [230]:

food_service=[]
food_taste=[]
food_temperature=[]


for i in range(len(vlstb)):
    if vlstb[i]=='service':
        food_service.append(vlsta[i])
    if vlstb[i]=='taste':
        food_taste.append(vlsta[i])
    if vlstb[i]=='temperature':
        food_temperature.append(vlsta[i])



food_service_d=collections.Counter(food_service)
food_service_d=OrderedDict(sorted(food_service_d.items(), key=itemgetter(1),reverse=True))
#sorted(food_service_d.items(), key=lambda x: x[1],reverse=True)

food_taste_d=collections.Counter(food_taste)
food_taste_d=OrderedDict(sorted(food_taste_d.items(), key=itemgetter(1),reverse=True))

food_temperature_d=collections.Counter(food_temperature)
food_temperature_d=OrderedDict(sorted(food_temperature_d.items(), key=itemgetter(1),reverse=True))

In [231]:
food_service_taste_d=dict()
for element in food_service_d.keys() & food_taste_d.keys():
#    print(element,min(food_service_d[element],food_taste_d[element]))
    food_service_taste_d[element]=min(food_service_d[element],food_taste_d[element])
food_service_taste_d=OrderedDict(sorted(food_service_taste_d.items(), key=itemgetter(1),reverse=True))   
food_service_taste_df=pd.DataFrame({'Word':list(food_service_taste_d.keys()),'Count':list(food_service_taste_d.values())})
    
food_service_temperature_d=dict()
for element in food_service_d.keys() & food_temperature_d.keys():
#    print(element,min(food_service_d[element],food_taste_d[element]))
    food_service_temperature_d[element]=min(food_service_d[element],food_temperature_d[element])
food_service_temperature_d=OrderedDict(sorted(food_service_temperature_d.items(), key=itemgetter(1),reverse=True))
food_service_temperature_df=pd.DataFrame({'Word':list(food_service_temperature_d.keys()),'Count':list(food_service_temperature_d.values())})

food_temperature_taste_d=dict()
for element in food_temperature_d.keys() & food_taste_d.keys():
#    print(element,min(food_service_d[element],food_taste_d[element]))
    food_temperature_taste_d[element]=min(food_temperature_d[element],food_taste_d[element])    
food_temperature_taste_d=OrderedDict(sorted(food_temperature_taste_d.items(), key=itemgetter(1),reverse=True))
food_temperature_taste_df=pd.DataFrame({'Word':list(food_temperature_taste_d.keys()),'Count':list(food_temperature_taste_d.values())})


food_service_taste_temperature_d=dict()
for element in food_service_taste_d.keys() & food_temperature_taste_d.keys():
#    print(element,min(food_service_taste_d[element],food_temperature_taste_d[element]))
    food_service_taste_temperature_d[element]=min(food_service_taste_d[element],food_temperature_taste_d[element])
food_service_taste_temperature_d=OrderedDict(sorted(food_service_taste_temperature_d.items(), key=itemgetter(1),reverse=True))
food_service_taste_temperature_df=pd.DataFrame({'Word':list(food_service_taste_temperature_d.keys()),'Count':list(food_service_taste_temperature_d.values())})

In [232]:
food_service_taste_df.where(food_service_taste_df['Count']==1).dropna()

           Word  Count
15      without    1.0
16      alright    1.0
17          two    1.0
18         okay    1.0
19         like    1.0
20         well    1.0
21         fine    1.0
22        awful    1.0
23        could    1.0
24          low    1.0
25        worst    1.0
26  interesting    1.0
27      awesome    1.0
28      amazing    1.0
29        super    1.0
30        cheap    1.0
31         high    1.0

In [233]:
food_service_temperature_df

        Word  Count
0     coffee      1
1     yogurt      1
2       poor      1
3      still      1
4        tea      1
5       warm      1
6  presented      1

In [234]:
food_temperature_taste_df

     Word  Count
0     dry      1
1  coffee      1

In [235]:
food_service_taste_temperature_df

     Word  Count
0  coffee      1

# Entertainment

In [236]:
entertainment_list=[]
entertainment_aspect_list=[]
entertainment_id_list=[]

df=pd.read_csv(r"C:/Users/Vaibhav/Downloads/FinalLabelsv2/FinalLabelsv2/Entertainment.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['Entertainment'].notna()]
entertainment_list.extend(df1['Entertainment'])
entertainment_id_list.extend(df1['id_updated'])
for asp in df1['Aspect']:
    entertainment_aspect_list.append(asp.lower())

r'''
df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/EntertainmentAspects.csv")
df3=df2[df2['Groups'].notna()]
df3=df3[df3['Entertainment'].notna()]
entertainment_list.extend(df3['Entertainment'])
entertainment_id_list.extend(df3['id'])
for asp in df3['Groups']:
    entertainment_aspect_list.append(asp.lower())
'''

'\ndf2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/EntertainmentAspects.csv")\ndf3=df2[df2[\'Groups\'].notna()]\ndf3=df3[df3[\'Entertainment\'].notna()]\nentertainment_list.extend(df3[\'Entertainment\'])\nentertainment_id_list.extend(df3[\'id\'])\nfor asp in df3[\'Groups\']:\n    entertainment_aspect_list.append(asp.lower())\n'

In [237]:
set(entertainment_aspect_list)

{'audio', 'general', 'visual'}

In [238]:
vlsta=[]
vlstb=[]
vlstid=[]

for i in range(len(entertainment_list)):
    entertainment_list[i]=entertainment_list[i].replace("n't",' not')
    #vlst=[w for w in entertainment_list[i].split() and w not in stop_words]
    for word in entertainment_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(entertainment_aspect_list[i])
                vlstid.append(entertainment_id_list[i]) 
    
df_entertainment_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')
#df_entertainment_new.to_csv(r'\entertainment_new.csv')

In [239]:
entertainment_audio=[]
entertainment_general=[]
entertainment_visual=[]


for i in range(len(vlstb)):
    if vlstb[i]=='audio':
        entertainment_audio.append(vlsta[i])
    if vlstb[i]=='general':
        entertainment_general.append(vlsta[i])
    if vlstb[i]=='visual':
        entertainment_visual.append(vlsta[i])



entertainment_audio_d=collections.Counter(entertainment_audio)
entertainment_audio_d=OrderedDict(sorted(entertainment_audio_d.items(), key=itemgetter(1),reverse=True))
#sorted(entertainment_audio_d.items(), key=lambda x: x[1],reverse=True)

entertainment_general_d=collections.Counter(entertainment_general)
entertainment_general_d=OrderedDict(sorted(entertainment_general_d.items(), key=itemgetter(1),reverse=True))

entertainment_visual_d=collections.Counter(entertainment_visual)
entertainment_visual_d=OrderedDict(sorted(entertainment_visual_d.items(), key=itemgetter(1),reverse=True))

In [240]:
entertainment_audio_general_d=dict()
for element in entertainment_audio_d.keys() & entertainment_general_d.keys():
#    print(element,min(entertainment_audio_d[element],entertainment_general_d[element]))
    entertainment_audio_general_d[element]=min(entertainment_audio_d[element],entertainment_general_d[element])
entertainment_audio_general_d=OrderedDict(sorted(entertainment_audio_general_d.items(), key=itemgetter(1),reverse=True))   
entertainment_audio_general_df=pd.DataFrame({'Word':list(entertainment_audio_general_d.keys()),'Count':list(entertainment_audio_general_d.values())})
    
entertainment_audio_visual_d=dict()
for element in entertainment_audio_d.keys() & entertainment_visual_d.keys():
#    print(element,min(entertainment_audio_d[element],entertainment_general_d[element]))
    entertainment_audio_visual_d[element]=min(entertainment_audio_d[element],entertainment_visual_d[element])
entertainment_audio_visual_d=OrderedDict(sorted(entertainment_audio_visual_d.items(), key=itemgetter(1),reverse=True))
entertainment_audio_visual_df=pd.DataFrame({'Word':list(entertainment_audio_visual_d.keys()),'Count':list(entertainment_audio_visual_d.values())})

entertainment_visual_general_d=dict()
for element in entertainment_visual_d.keys() & entertainment_general_d.keys():
#    print(element,min(entertainment_audio_d[element],entertainment_general_d[element]))
    entertainment_visual_general_d[element]=min(entertainment_visual_d[element],entertainment_general_d[element])    
entertainment_visual_general_d=OrderedDict(sorted(entertainment_visual_general_d.items(), key=itemgetter(1),reverse=True))
entertainment_visual_general_df=pd.DataFrame({'Word':list(entertainment_visual_general_d.keys()),'Count':list(entertainment_visual_general_d.values())})


entertainment_audio_general_visual_d=dict()
for element in entertainment_audio_general_d.keys() & entertainment_visual_general_d.keys():
#    print(element,min(entertainment_audio_general_d[element],entertainment_visual_general_d[element]))
    entertainment_audio_general_visual_d[element]=min(entertainment_audio_general_d[element],entertainment_visual_general_d[element])
entertainment_audio_general_visual_d=OrderedDict(sorted(entertainment_audio_general_visual_d.items(), key=itemgetter(1),reverse=True))
entertainment_audio_general_visual_df=pd.DataFrame({'Word':list(entertainment_audio_general_visual_d.keys()),'Count':list(entertainment_audio_general_visual_d.values())})

In [241]:
entertainment_audio_general_df

            Word  Count
0         system      2
1           poor      2
2  entertainment      2
3           good      2
4        working      1
5        quality      1
6            bad      1

In [242]:
entertainment_audio_visual_df

            Word  Count
0           poor      2
1  entertainment      2
2           good      2
3         system      1
4            new      1
5        working      1
6        quality      1

In [243]:
entertainment_visual_general_df

              Word  Count
0    entertainment     10
1             good      8
2        selection      6
3              old      4
4          working      3
5             work      3
6            great      3
7               ok      2
8             poor      2
9           choice      2
10            huge      1
11         ancient      1
12          broken      1
13          better      1
14         quality      1
15         choices      1
16         limited      1
17       streaming      1
18            wide      1
19            seat      1
20  malfunctioning      1
21          access      1
22           broke      1
23           quite      1
24        personal      1
25          system      1
26          decent      1
27         content      1
28      nonworking      1
29       excellent      1
30        outdated      1
31          recent      1
32          looked      1

# Off flight

In [244]:
offflight_list=[]
offflight_aspect_list=[]
offflight_id_list=[]

df=pd.read_csv(r"C:\Users\Vaibhav\Downloads\FinalLabelsv2\FinalLabelsv2/Off.csv")
df1=df[df['Aspect'].notna()]
df1=df1[df1['Off-flight service'].notna()]
offflight_list.extend(df1['Off-flight service'])
offflight_id_list.extend(df1['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df1['Aspect']:
    offflight_aspect_list.append(asp.lower())
r'''

df2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/OffFlightAspects.csv")
df3=df2[df2['Groups'].notna()]
df3=df3[df3['Off-flight service'].notna()]
offflight_list.extend(df3['Off-flight service'])
offflight_id_list.extend(df3['id'])
#aspect_list=list(df1['Aspect'])
for asp in df3['Groups']:
    offflight_aspect_list.append(asp.lower())
    
df4=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/Off-flight service1_ticketing.csv")
df5=df4[df4['Aspect'].notna()]
df5=df5[df5['Bookings'].notna()]
offflight_list.extend(df5['Bookings'])
offflight_id_list.extend(df5['id_updated'])
#aspect_list=list(df1['Aspect'])
for asp in df5['Aspect']:
    offflight_aspect_list.append(asp.lower())
'''

'\n\ndf2=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/OffFlightAspects.csv")\ndf3=df2[df2[\'Groups\'].notna()]\ndf3=df3[df3[\'Off-flight service\'].notna()]\noffflight_list.extend(df3[\'Off-flight service\'])\noffflight_id_list.extend(df3[\'id\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df3[\'Groups\']:\n    offflight_aspect_list.append(asp.lower())\n    \ndf4=pd.read_csv(r"C:/Users/Vaibhav/Documents/GitHub/Aspect-Based-Sentiment-Analysis/data/restaurants/Off-flight service1_ticketing.csv")\ndf5=df4[df4[\'Aspect\'].notna()]\ndf5=df5[df5[\'Bookings\'].notna()]\noffflight_list.extend(df5[\'Bookings\'])\noffflight_id_list.extend(df5[\'id_updated\'])\n#aspect_list=list(df1[\'Aspect\'])\nfor asp in df5[\'Aspect\']:\n    offflight_aspect_list.append(asp.lower())\n'

In [245]:
set(offflight_aspect_list)

{'facility', 'general', 'ticketing'}

In [246]:
vlsta=[]
vlstb=[]
vlstid=[]

for i in range(len(offflight_list)):
    offflight_list[i]=offflight_list[i].replace("n't",' not')
    #vlst=[w for w in offflight_list[i].split() and w not in stop_words]
    for word in offflight_list[i].split():
            if word not in stop_words:
                vlsta.append(word)
                vlstb.append(offflight_aspect_list[i])
                vlstid.append(offflight_id_list[i]) 

df_offflight_new=pd.DataFrame({'id':vlstid,'Word':vlsta,'Aspect':vlstb}).sort_values(by='Aspect')
#df_offflight_new.to_csv(r'\offflight_new.csv')

In [247]:
len(vlsta)

4551

In [248]:
len(list(set(vlsta)))

1116

In [249]:
offflight_facility=[]
offflight_general=[]
offflight_operations=[]
offflight_ticketing=[]

for i in range(len(vlstb)):
    if vlstb[i]=='facility':
        offflight_facility.append(vlsta[i])
    if vlstb[i]=='general':
        offflight_general.append(vlsta[i])
    if vlstb[i]=='operations':
        offflight_operations.append(vlsta[i])
    if vlstb[i]=='ticketing':
        offflight_ticketing.append(vlsta[i])



offflight_facility_d=collections.Counter(offflight_facility)
offflight_facility_d=OrderedDict(sorted(offflight_facility_d.items(), key=itemgetter(1),reverse=True))
#sorted(offflight_facility_d.items(), key=lambda x: x[1],reverse=True)

offflight_general_d=collections.Counter(offflight_general)
offflight_general_d=OrderedDict(sorted(offflight_general_d.items(), key=itemgetter(1),reverse=True))

offflight_operations_d=collections.Counter(offflight_operations)
offflight_operations_d=OrderedDict(sorted(offflight_operations_d.items(), key=itemgetter(1),reverse=True))

offflight_ticketing_d=collections.Counter(offflight_ticketing)
offflight_ticketing_d=OrderedDict(sorted(offflight_ticketing_d.items(), key=itemgetter(1),reverse=True))

In [250]:
offflight_facility_general_d=dict()
for element in offflight_facility_d.keys() & offflight_general_d.keys():
#    print(element,min(offflight_facility_d[element],offflight_general_d[element]))
    offflight_facility_general_d[element]=min(offflight_facility_d[element],offflight_general_d[element])
offflight_facility_general_d=OrderedDict(sorted(offflight_facility_general_d.items(), key=itemgetter(1),reverse=True))   
offflight_facility_general_df=pd.DataFrame({'Word':list(offflight_facility_general_d.keys()),'Count':list(offflight_facility_general_d.values())})
    
offflight_facility_operations_d=dict()
for element in offflight_facility_d.keys() & offflight_operations_d.keys():
#    print(element,min(offflight_facility_d[element],offflight_general_d[element]))
    offflight_facility_operations_d[element]=min(offflight_facility_d[element],offflight_operations_d[element])
offflight_facility_operations_d=OrderedDict(sorted(offflight_facility_operations_d.items(), key=itemgetter(1),reverse=True))
offflight_facility_operations_df=pd.DataFrame({'Word':list(offflight_facility_operations_d.keys()),'Count':list(offflight_facility_operations_d.values())})

offflight_operations_general_d=dict()
for element in offflight_operations_d.keys() & offflight_general_d.keys():
#    print(element,min(offflight_facility_d[element],offflight_general_d[element]))
    offflight_operations_general_d[element]=min(offflight_operations_d[element],offflight_general_d[element])    
offflight_operations_general_d=OrderedDict(sorted(offflight_operations_general_d.items(), key=itemgetter(1),reverse=True))
offflight_operations_general_df=pd.DataFrame({'Word':list(offflight_operations_general_d.keys()),'Count':list(offflight_operations_general_d.values())})

offflight_facility_ticketing_d=dict()
for element in offflight_facility_d.keys() & offflight_ticketing_d.keys():
#    print(element,min(offflight_facility_d[element],offflight_general_d[element]))
    offflight_facility_ticketing_d[element]=min(offflight_facility_d[element],offflight_ticketing_d[element])
offflight_facility_ticketing_d=OrderedDict(sorted(offflight_facility_ticketing_d.items(), key=itemgetter(1),reverse=True))
offflight_facility_ticketing_df=pd.DataFrame({'Word':list(offflight_facility_ticketing_d.keys()),'Count':list(offflight_facility_ticketing_d.values())})
    
offflight_general_ticketing_d=dict()
for element in offflight_general_d.keys() & offflight_ticketing_d.keys():
#    print(element,min(offflight_general_d[element],offflight_general_d[element]))
    offflight_general_ticketing_d[element]=min(offflight_general_d[element],offflight_ticketing_d[element])
offflight_general_ticketing_d=OrderedDict(sorted(offflight_general_ticketing_d.items(), key=itemgetter(1),reverse=True))
offflight_general_ticketing_df=pd.DataFrame({'Word':list(offflight_general_ticketing_d.keys()),'Count':list(offflight_general_ticketing_d.values())})
   
offflight_operations_ticketing_d=dict()
for element in offflight_operations_d.keys() & offflight_ticketing_d.keys():
#    print(element,min(offflight_operations_d[element],offflight_operations_d[element]))
    offflight_operations_ticketing_d[element]=min(offflight_operations_d[element],offflight_ticketing_d[element])
offflight_operations_ticketing_d=OrderedDict(sorted(offflight_operations_ticketing_d.items(), key=itemgetter(1),reverse=True))
offflight_operations_ticketing_df=pd.DataFrame({'Word':list(offflight_operations_ticketing_d.keys()),'Count':list(offflight_operations_ticketing_d.values())})

In [251]:
x=dict()
offflight_facility_operations_general_ticketing_d=dict() #all
for element in offflight_operations_general_d.keys() & offflight_facility_d.keys():
#    print(element,min(offflight_operations_d[element],offflight_operations_d[element]))
    x[element]=min(offflight_operations_general_d[element],offflight_facility_d[element])
x=OrderedDict(sorted(x.items(), key=itemgetter(1),reverse=True))
for element in x.keys() & offflight_ticketing_d.keys():
    offflight_facility_operations_general_ticketing_d[element]=min(x[element],offflight_ticketing_d[element])
offflight_facility_operations_general_ticketing_d=OrderedDict(sorted(offflight_facility_operations_general_ticketing_d.items(), key=itemgetter(1),reverse=True))
offflight_facility_operations_general_ticketing_df=pd.DataFrame({'Word':list(offflight_facility_operations_general_ticketing_d.keys()),'Count':list(offflight_facility_operations_general_ticketing_d.values())})

In [252]:
offflight_facility_general_df.where(offflight_facility_general_df['Count']==1).dropna()

             Word  Count
18           best    1.0
19      confusing    1.0
20          wrong    1.0
21           info    1.0
22        message    1.0
23          track    1.0
24    immediately    1.0
25      automatic    1.0
26      selection    1.0
27      organized    1.0
28         breeze    1.0
29        reached    1.0
30      available    1.0
31          fully    1.0
32           long    1.0
33           free    1.0
34           done    1.0
35           nice    1.0
36      dedicated    1.0
37       problems    1.0
38          worst    1.0
39            bad    1.0
40         prompt    1.0
41    performance    1.0
42       painless    1.0
43           poor    1.0
44       smoothly    1.0
45          prior    1.0
46         access    1.0
47          worse    1.0
48        several    1.0
49         hassle    1.0
50          quite    1.0
51           page    1.0
52           trip    1.0
53           slow    1.0
54        failing    1.0
55              ’    1.0
56        refused    1.0
57           back    1.0
58  communication    1.0

In [253]:
offflight_facility_operations_df

Empty DataFrame
Columns: [Word, Count]
Index: []

In [254]:
offflight_operations_general_df.where(offflight_operations_general_df['Count']==1).dropna()

Empty DataFrame
Columns: [Word, Count]
Index: []

In [255]:
offflight_facility_ticketing_df

             Word  Count
0         process      4
1            easy      3
2            good      3
3           great      3
4       excellent      2
5            best      1
6            huge      1
7             air      1
8            info      1
9           found      1
10          fully      1
11           took      1
12         smooth      1
13           free      1
14           done      1
15  reimbursement      1
16        premium      1
17        layover      1
18       slightly      1
19           trip      1
20         decent      1
21        refused      1
22         forced      1
23           back      1

In [256]:
offflight_general_ticketing_df.where(offflight_general_ticketing_df['Count']==2).dropna()

          Word  Count
9          way    2.0
10   excellent    2.0
11      return    2.0
12  impossible    2.0
13      travel    2.0
14   complaint    2.0
15      trying    2.0
16       error    2.0
17        best    2.0
18      really    2.0
19        zero    2.0
20        kept    2.0
21     upgrade    2.0
22      pretty    2.0

In [257]:
offflight_operations_ticketing_df

Empty DataFrame
Columns: [Word, Count]
Index: []

In [258]:
len(offflight_list)

5866

In [259]:
df_offflight_new.head()

          id      Word    Aspect
0       2946     check  facility
1282    3711     check  facility
1281    3711  checking  facility
1280    3711     kiosk  facility
3206  202921    called  facility

In [260]:
cmn = list(set(list(set(list(df_inflight_new['Word'])).intersection(list(df_offflight_new['Word'])))))

In [261]:
len(cmn)

200

In [262]:
cmn

['issues',
 'new',
 'business',
 'ignored',
 'pay',
 'program',
 'timely',
 'experience',
 'tight',
 'better',
 'plane',
 'always',
 'loyalty',
 'without',
 'good',
 'times',
 'management',
 'waiting',
 'shocking',
 'disappointed',
 'terrible',
 'could',
 'maintained',
 'reasonable',
 'worst',
 'deal',
 'seats',
 'ok',
 'much',
 'basic',
 'frustrating',
 'amazing',
 'disorganised',
 'operations',
 'horrible',
 'flight',
 'ran',
 'way',
 'upgraded',
 'gone',
 'top',
 'forced',
 'cold',
 'excellent',
 'worked',
 'route',
 'great',
 'needs',
 'higher',
 'paper',
 'customer',
 'non',
 'huge',
 'staff',
 'got',
 'special',
 'silver',
 'working',
 'services',
 'ontime',
 'info',
 'onboard',
 'passengers',
 'extras',
 'inconvenience',
 'problem',
 'impossible',
 'took',
 'smooth',
 'cards',
 'boarded',
 'quicker',
 'offer',
 'delivery',
 'arrival',
 'lie',
 'bad',
 'welcome',
 'pathetic',
 'fast',
 'pack',
 'everything',
 'friendly',
 'travel',
 'clean',
 'time',
 'outstanding',
 'quite',
 'care',
 'deck',
 'impressed',
 'deboarding',
 'cheap',
 'used',
 'high',
 'comfortable',
 'service',
 'lack',
 'face',
 'air',
 'perfect',
 'receive',
 'unacceptable',
 'card',
 'first',
 'bag',
 'voucher',
 'charging',
 'quality',
 'organized',
 'airline',
 'poorly',
 'rubbish',
 'boarding',
 'delayed',
 'maintenance',
 'level',
 'limited',
 'unhappy',
 'appalling',
 'purchase',
 'small',
 'class',
 'atrocious',
 'organisation',
 'nice',
 'board',
 'impressive',
 'offered',
 'vouchers',
 'seat',
 'priority',
 'low',
 'prompt',
 'technical',
 'checking',
 'satisfactory',
 'quick',
 'rerouted',
 'poor',
 'economy',
 'call',
 'member',
 'extremely',
 'comfort',
 'joke',
 'superb',
 'fly',
 'best',
 'really',
 'connection',
 'boring',
 'wheel',
 'option',
 'helpful',
 'cost',
 'professional',
 'went',
 'dirty',
 'planning',
 'unorganized',
 'meal',
 'punctual',
 'work',
 'provided',
 'announcements',
 'discount',
 'available',
 'minimal',
 'well',
 'free',
 'kept',
 'fine',
 'paid',
 'request',
 'properly',
 'lighting',
 'far',
 'pleasant',
 'pocket',
 'getting',
 'fantastic',
 'use',
 'expectations',
 'flawless',
 'worse',
 'cattle',
 'super',
 'convenient',
 'choice',
 'slow',
 'efficient',
 'ridiculous',
 'buy',
 'delays',
 'extra',
 'communication',
 'provide',
 'delay',
 'belt']

In [263]:
#Restrucuring aspects

In [264]:
import pandas as pd

In [265]:
#inf_fac=['business','wifi','class']
#inf_ops=['time','inflight','flight','customer']

#st_gen=['flight','customer','announcements','announcement','announce', 'announced','air','people','management']
#st_beh=['help','helpful','assist','communication','care','caring','assisstance','assistance','friendly','friendliness','trained','ignored','speak','apology','answer','special','responsibility','apologies','refused']

#pos_gen=['lugguage','lugage','luguage','luggage','lugguages','bag','bagg','baggs','backpack','baggages','baggage','suitcase','bags','suitcases','items','claim','claims','ugguage']
#pos_han=['check','checked','delivered','transfer','wasted','allow','allowed','allowance','weigh','lost','missing','left','handling']

se_cm=['leg','legroom','recline','reclining','back','room','flat','rest','room','pushback','little','table']
se_op=['broken','old','rubbish','cover','covered','seat','seats','seating','configuration','pockets','chair','covers','button','damage','damaged']

In [266]:
df=pd.read_csv(r'C:/Users/Vaibhav/Downloads/FinalLabels/FinalLabels/Seat.csv')

In [267]:
set(df['Aspect'])

{'comfort', 'operations', 'space'}

In [268]:
df['Aspect']=df['Aspect'].apply(lambda x: 'comfort' if x=='space' else x)

In [269]:
df['Aspect']=df['Aspect'].apply(lambda x: 'comfort' if x in se_cm else 'operations' if x in se_op else x)

In [270]:
df.to_csv(r'C:/Users/Vaibhav/Downloads/FinalLabels/FinalLabels/New final/Seat.csv')

In [271]:
df.head(10)

   Unnamed: 0  Unnamed: 0.1      id         Seat      Aspect  id_updated
0           0            15  2948.0          leg     comfort      2948.0
1           1            15  2948.0         room     comfort      2948.0
2           2            16  2948.0        chose  operations      2948.0
3           3            20  2950.0      massage  operations      2950.0
4           4            20  2950.0     function  operations      2950.0
5           5            21  2950.0    excellent  operations      2950.0
6           6            21  2950.0     business  operations      2950.0
7           7            21  2950.0        class  operations      2950.0
8           8            21  2950.0        seats  operations      2950.0
9           9            35  2952.0  comfortable     comfort      2952.0